package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"fmt"

	"github.com/bottlehub/unboard/boards/graph/model"
	"github.com/bottlehub/unboard/boards/internals/database"
)

// CreateTimeline is the resolver for the createTimeline field.
func (r *mutationResolver) CreateTimeline(ctx context.Context, input model.NewTimeline) (*model.Timeline, error) {
	panic(fmt.Errorf("not implemented: CreateTimeline - createTimeline"))
}

// UpdateTimeline is the resolver for the updateTimeline field.
func (r *mutationResolver) UpdateTimeline(ctx context.Context, id string, input model.UpdateTimeline) (*model.Timeline, error) {
	panic(fmt.Errorf("not implemented: UpdateTimeline - updateTimeline"))
}

// DeleteTimeline is the resolver for the deleteTimeline field.
func (r *mutationResolver) DeleteTimeline(ctx context.Context, id string) (*model.DeleteTimeline, error) {
	panic(fmt.Errorf("not implemented: DeleteTimeline - deleteTimeline"))
}

// Timelines is the resolver for the timelines field.
func (r *queryResolver) Timelines(ctx context.Context, input model.Fetch) ([]*model.Timeline, error) {
	panic(fmt.Errorf("not implemented: Timelines - timelines"))
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, input model.Fetch) (*model.Timeline, error) {
	panic(fmt.Errorf("not implemented: Timeline - timeline"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var (
	db, _ = database.ConnectDB()
)
