// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type DeleteTimeline struct {
	ID string `json:"id"`
}

type Fetch struct {
	ID string `json:"id"`
}

type NewTimeline struct {
	PostedBy string  `json:"postedBy"`
	PostedOn string  `json:"postedOn"`
	ImageURL *string `json:"imageURL,omitempty"`
	Text     *string `json:"text,omitempty"`
	Like     int     `json:"like"`
}

type Timeline struct {
	ID           string      `json:"id"`
	PostedBy     *User       `json:"postedBy"`
	PostedOn     *Timeline   `json:"postedOn"`
	ImageURL     *string     `json:"imageURL,omitempty"`
	Text         *string     `json:"text,omitempty"`
	Likes        int         `json:"likes"`
	SubTimelines []*Timeline `json:"subTimelines,omitempty"`
}

type UpdateTimeline struct {
	Name        *string `json:"name,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
	Text        *string `json:"text,omitempty"`
	SubTimeline *string `json:"subTimeline,omitempty"`
}

type User struct {
	ID             string  `json:"id"`
	Username       string  `json:"username"`
	Name           string  `json:"name"`
	About          *string `json:"about,omitempty"`
	AvatarImageURL string  `json:"avatarImageURL"`
	Following      []*User `json:"following,omitempty"`
	Followers      []*User `json:"followers,omitempty"`
}

type Status string

const (
	StatusNotStarted Status = "NOT_STARTED"
	StatusInProgress Status = "IN_PROGRESS"
	StatusCompleted  Status = "COMPLETED"
)

var AllStatus = []Status{
	StatusNotStarted,
	StatusInProgress,
	StatusCompleted,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusNotStarted, StatusInProgress, StatusCompleted:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
