name: Publish Image to Docker Hub
on:
  pull_request:
    branches: [ master ]

jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@latest
            - name: build
              run: |
                docker build . -t lordewan/boards:latest
            - name: publish
              run: |
                docker login -u lordewan -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker push lordewan/boards:latest
