name: Publish Image to Docker Hub

on:
  pull_request:
    branches: [main]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: build
        run: |
          docker build . -t lordewan/boards:latest
        working-directory: ./boards
      - name: publish
        run: |
          docker login -u lordewan -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push lordewan/boards:latest
        working-directory: ./boards
      - name: deploy app
        env:
            MONGOURI: ${{ secrets.MONGOURI }}
            RABBITMQ: ${{ secrets.RABBITMQ }}
        run: flyctl deploy --remote-only
        working-directory: ./boards
