name: Publish Image to Docker Hub
on:
  [push, pull_request]

jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: build
              run: |
                docker build . -t lordewan/boards:latest
              working-directory: ./boards
            - name: publish
              run: |
                docker login -u lordewan -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker push lordewan/boards:latest
              working-directory: ./boards
